# config.yml für LongEval Task 1 - WebRetrieval

general:
  project_name: longeval2025_webretrieval
  team_name: AIR5
  task: WebRetrieval
  language: French
  output_dir: ./runs/

data:
  data_dir: ./data/lag6_lag8_subset/French
  train_collection: LongEval Train Collection
  lag6_qrels_dir: qrels/2022-11_fr
  lag8_qrels_dir: qrels/2023-01_fr
  queries_file: queries.trec

bm25:
  k1: 1.2
  b: 0.75
  top_k: 25
  index_dir: ./index/bm25/

evaluation:
  metrics: [nDCG@10, P@10, Relative_nDCG_Drop]
  lags: [Lag6, Lag8]

