# config.yml für LongEval Task 1 - WebRetrieval

general:
  project_name: longeval2025_webretrieval
  team_name: AIR5
  task: WebRetrieval
  language: French
  output_dir: ./runs/

data:
  data_dir: ./data/release_2025/French/
  train_collection: LongEval\ Train\ Collection
  qrels_dir: qrels/
  queries_file: queries.txt

bm25:
  k1: 1.2
  b: 0.75
  top_k: 1000
  index_dir: ./index/bm25/

evaluation:
  metrics: [nDCG@10, P@10, Relative_nDCG_Drop]
  lags: [Lag6, Lag8]

