# config.yml für LongEval Task 1 - WebRetrieval

general:
  project_name: longeval2025_webretrieval
  team_name: AIR5
  task: WebRetrieval
  language: French
  output_dir: ./runs/

data:
  data_dir: ./data/release_2025_june_subset/French/  #DONE
  train_collection: LongEval Train Collection   #DONE
  qrels_dir: qrels/
  queries_file: queries.trec #DONE

bm25:
  k1: 1.2  #DONE
  b: 0.75  #DONE
  top_k: 100  #DONE
  index_dir: ./index/bm25/   #DONE

evaluation:
  metrics: [nDCG@10, P@10, Relative_nDCG_Drop]
  lags: [Lag6, Lag8]

